openapi: 3.0.0
info:
  title: Running Stats API
  description: This API receive post-workout information from a smartwatch
  contact:
    email: tle172@my.bcit.ca
  version: 1.0.0
servers:
- url: /
tags:
- name: smartwatches
  description: Samsung Smartwatches running Wear OS 5.0 and above
- name: developers
  description: Operations available to regular developers
paths:
  /stats/running:
    get:
      summary: Get running stats
      operationId: app.get_running_stats
      description: Get running stats within a date range
      parameters:
        - in: query
          name: start_timestamp
          schema:
            type: string
            format: date-time
          required: true
          description: Start of date range
        - in: query
          name: end_timestamp
          schema:
            type: string
            format: date-time
          required: true
          description: End of date range
      responses:
        '200':
          description: Successfully returned a list of running stats
          content:
            application/json:    
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RunningStats'
  /stats/music:
    get:
      summary: Get music info
      operationId: app.get_music_info
      description: Get music info within a date range
      parameters:
        - in: query
          name: start_timestamp
          schema:
            type: string
            format: date-time
          required: true
          description: Start of date range
        - in: query
          name: end_timestamp
          schema:
            type: string
            format: date-time
          required: true
          description: End of date range
      responses:
        '200':
          description: Successfully returned a list of music info
          content:
            application/json:    
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MusicInfo'
  /stats:
    get:
      summary: gets the event stats  
      operationId: app.get_event_stats
      description: Gets the stats of the history events
      responses:
        '200':
          description: Successfully returned the event stats
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stats'
  

components:
  schemas:
    RunningStats:
      required:
      - distance
      - duration
      - timestamp
      - user_id
      - trace_id
      type: object
      properties:
        user_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        duration:
          type: number
          example: 3600
        distance:
          type: number
          example: 5000
        timestamp:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        trace_id:
          type: string
          format: uuid
          example: f058ebd6-02f7-4d3f-942e-904344e8cde5
    MusicInfo:
      required:
      - artist
      - song_duration
      - song_name
      - timestamp
      - user_id
      - trace_id
      type: object
      properties:
        user_id:
          type: string
          format: uuid
          example: d999f1ee-6c54-4b01-90e6-d701748f0851
        song_name:
          type: string
          example: Run Boy Run
        artist:
          type: string
          example: Woodkid
        song_duration:
          type: number
          example: 180
        timestamp:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        trace_id:
          type: string
          format: uuid
          example: f058ebd6-02f7-4d3f-942e-904344e8cde5
    Stats:
      type: object
      required:
        - num_running_stats
        - num_music_info
      properties:
        num_running_stats:
          type: integer
          example: 100
        num_music_info: 
          type: integer
          example: 100
